name = "StatMeta"
uuid = "216efad7-dd5d-4dce-bd96-1d53de06eee1"
authors = ["pdaman"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
